---
omz_dependencies:
  - git
  - zsh
# ommit the repo attribute if the plugin is in the default plugin dir
omz_plugins:
  - name: "git"
  - name: "zsh-autosuggestions"
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
  - name: "zsh-syntax-highlighting"
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"