---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true

- name: "Installing apt Packages"
  package:
    name:
      - hydra
      - curl
      - nmap
      - wireshark
      - nikto
      - ruby
      - ruby-dev
      - hashcat
      - tcpdump
      - gobuster
      - ffuf
      - cewl
      - tmux
      - php
      - smbclient
      - snmp
      - onesixtyone
      - mysql-client
      - nfs-common
      - jq
      - whois
      - proxychains4
      - freerdp2-x11
    state: latest
  become: true
