---
- name: "Check if metasploit is installed"
  stat: 
    path : "/usr/bin/msfconsole"
  register: msfconsole_stat

- name: "Install metasploit"
  shell: "curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb -o /tmp/msfinstall && chmod 755 /tmp/msfinstall && /tmp/msfinstall && rm /tmp/msfinstall"
  when: not msfconsole_stat.stat.exists

- name: "Clone sqlmap repo"
  git:
    repo: "https://github.com/sqlmapproject/sqlmap.git"
    dest: "/opt/sqlmap"

- name: "Check if John is installed"
  stat: 
    path : "/opt/john"
  register: john_stat

- name: "Install john"
  shell: "git clone https://github.com/openwall/john.git /opt/john && cd /opt/john/src && ./configure --without-openssl && make "
  when: not john_stat.stat.exists

- name: "Clone Responder repo"
  git:
    repo: "https://github.com/lgandx/Responder"
    dest: "/opt/responder"

- name: "Clone seclists repo"
  become: true
  git:
    name: "https://github.com/danielmiessler/SecLists.git"
    dest: "/usr/share/seclists"
    # make sure that this command doesn't error once the rockyou.tar.gz is unzipped
    update: false

- name: "Check if feroxbuster is installed"
  stat: 
    path : "/home/{{ ansible_env.USER }}/.local/bin/feroxbuster"
  register: feroxbuster_stat

- name: "Install feroxbuster"
  shell: "curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/main/install-nix.sh | bash -s $HOME/.local/bin"
  when: not feroxbuster_stat.stat.exists

- name: "Check if Obsidian is installed"
  stat: 
    path : "/usr/bin/obsidian"
  register: obsidian_stat


- name: "Install Obsidian"
  become: true
  apt:
    deb: "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.3.5/obsidian_1.3.5_amd64.deb"
  when: not obsidian_stat.stat.exists

- name: "Clone username-anarchy repo"
  git:
    name: "https://github.com/urbanadventurer/username-anarchy.git"
    dest: "/opt/username-anarchy"

- name: "Clone ntlm_theft repo"
  git:
    name: "https://github.com/Greenwolf/ntlm_theft.git"
    dest: "/opt/ntlm_theft"

- name: "Clone sherlock repo"
  git: 
    name: "https://github.com/sherlock-project/sherlock.git"
    dest: "/opt/sherlock"

- name: "Install sherlock dependencies"
  pip:
    requirements: "/opt/sherlock/requirements.txt"

- name: "Install GEF"
  shell: 'bash -c "$(wget https://gef.blah.cat/sh -O -)"'

- name: "Check if Ghidra is installed"
  stat: 
    path : "/opt/ghidra_11.0_PUBLIC/"
  register: ghidra_stat

- name: "Download and extract Ghidra"
  unarchive:
    remote_src: true
    src: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.0_build/ghidra_11.0_PUBLIC_20231222.zip"
    dest: "/opt/"
  when: not ghidra_stat
- name: "Copy the ghidra_auto.py script"
  copy: 
    src: "files/ghidra_auto.py"
    dest: "/opt/ghidra_auto.py"