---
- name: "Create policies dir"
  become: true
  file:
    path: "/etc/firefox/policies"
    state: "directory"
    mode: "0755"

- name: "Create custom_certs dir"
  become: true
  file:
    path: "/etc/firefox/custom_certs"
    state: "directory"
    mode: "0755"

- name: "Copy PortSwigger CA cert to custom_certs dir"
  become: true
  copy:
    src: "{{ burpsuite_dir }}/extras/PortSwigger_CA.der"
    dest: "/etc/firefox/custom_certs/PortSwigger_CA.der"

- name: "Write the policies.json template file"
  become: true
  template: 
    src: "{{ role_path }}/templates/policies.json.j2"
    dest: "/etc/firefox/policies/policies.json"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0664"