---
- name: "Change ownership of /opt directory"
  become: true
  become_method: "sudo"
  file:
    path: "/opt"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0755"
