---
- name: "Change ownership of /opt directory"
  become: true
  file:
    path: "/opt"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0755"

- name: "Mount VMware shared folders on startup"
  become: true
  lineinfile:
    path: "/etc/fstab"
    line: "#.host:/    /mnt/hgfs/    fuse.vmhgfs-fuse    defaults,allow_other,uid=1000     0    0"

- name: "Download rockyou.txt"
  get_url:
    dest: "/opt/rockyou.txt"
    url: "https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt"

- name: "Add ~/.local/bin to $PATH"
  lineinfile: 
    path:  "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=$PATH:{{ ansible_env.USER }}/.local/bin"
    insertafter: EOF
  