---
# inspired by https://github.com/IppSec/parrot-build/blob/master/roles/customize-terminal/tasks/main.yml
- name: "Install dependencies"
  pip:
    name: "psutil"

- name: "Read current gnome terminal profiles"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/list"
    state: "read"
  register: "profile_list"

- name: "Set profile_list if it doesn't exist"
  set_fact:
    profile_list:
      value: '["default"]'
  when: profile_list.value is none

- name: "Restoring my profile from dump"
  shell:
    cmd: "dconf load /org/gnome/terminal/legacy/profiles:/ < {{ role_path }}/files/dconf-profiles-dump"
  # only load once
  when: "'d28cbbb3-9ec2-47d4-92a7-c2960facbcc6' not in profile_list.value"
